spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todolistrest
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
