jwt:
  secret:
  lifetime: 20m

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todolistrest
    username:
    password:
    driverClassName: org.postgresql.Driver
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: create-drop
