jwt:
  secret: H9qKJMrBzF9NFaSmK7DwyGLx6G2qFwff  # 256 bit secret
  lifetime: 20m

spring:
  datasource:
    url:
    username:
    password:
    driverClassName: org.postgresql.Driver
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: create-drop
